let separator = java.io.File.separator;
run("chatutils.js");
setUpChat2();
DMessage("main: Beginning");
run("mediautils.js");
DMessage("Setting up media");
setUpMedia();
run("personalityutils.js");
DMessage("Setting up personality");
setUpVars();
run("TAIUtils.js");
setUpTAIUtils();
run("helperFunctions.js");
setVar("dommelevel",7);
setVar("hasChastity",true);
setVar("ballTorture",true);
setVar("cockTorture",true);
setVar("cbtBallLevel",3);
setVar("cbtCockLevel",3);
setVar("edgingmode", "Normal");
delVar("edginggoto");


//showCategoryVideo(randomCategory());
//playVideo("Videos" + java.io.File.separator + "AV_Clips" + java.io.File.separator + "webm" + java.io.File.separator + "60" + java.io.File.separator + "*.mp4");
//stopVideoAfter(45);
//unlockImages();
//CMessage("done");
//CMessage("%stroketaunt1%");
//CMessage("%stroketaunt1%");
//CMessage("%stroketaunt1%");
//CMessage("%stroketaunt1%");
//CMessage("%stroketaunt1%");
//CMessage("%stroketaunt1%");
//sleep(60);
Stroking();
setVar("ExtremeHold",70);
setVar("LongHold",70);
holdEdge();
holdEdge();
holdEdge();
holdEdge();
CMessage("%greetsub%");
CMessage("%GeneralTime%, %DomHonnorific%");
Stroking();
sleep(60);
playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
	sleep(2);
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
	sleep(2);
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
	sleep(2);
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
    CMessage("%pthevCaningTaunts%");
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
    CMessage("%pthevCaningTaunts%");
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
    CMessage("%pthevCaningTaunts%");
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
    CMessage("%pthevCaningTaunts%");
    playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "whip.mp3");
    CMessage("%pthevCaningTaunts%");
sleep(65);
CMessage("done");
    sleep(randomInt(20, 40));
	stopVideo();
	CMessage("done");
//increasePace();
//setTempVar("moduletorun", "Modules" + java.io.File.separator + "AV_ModGeneral23.js");
//run("Structure" + separator + "HoTStructure.js");
//CMessage("done");
//sleep(10);
//setDate("AV_SessionTime");
//setVar("AV_ModGeneral4", 111);
//SMessage("<c=green %AV_GirlName% : >%AV_ShowOmelegPics%<c=black b>%AV_OmLegStroke% ");
//SMessage("<c=green b>%AV_GirlName% : <c=black b>@"+random("Hurry up and get close for me", "I hope you're not let letting yourself get distracted over there", "Faster %SubName%, I want you on that edge right now"));
//CMessage("%AV_ShowOmelegPics% ",0);
//sleep(randomInt(10,15) );
//playVideo("Videos" + java.io.File.separator +"webcamshow01.mp4");
//playVideo("Videos" + java.io.File.separator + "AV_Clips" + java.io.File.separator + "webm" + java.io.File.separator + "60" + java.io.File.separator + "*.mp4",true);
//playVideo("Videos" + java.io.File.separator +"0012.mp4");
//CMessage("wait10");
//sleep(10);
//CMessage("%pthevCoCo1%");
//playVideo("Videos" + java.io.File.separator + "AV_Clips" + java.io.File.separator + "cam" + java.io.File.separator + "webcamshow02.mp4");
//sleep(30);
//CMessage("%AV_RepeatAL%	%DeniyMe% %1_ST_Stroke%	%AV_AudioBeat% %AV_GreenLight%	%RedLight% %GNMCheerEdgeATon% %PunishGame% %AV_GlittersGame% %secondtime% %FYI%	%DoAsISay%");
//holdEdgeWT("So get on the edge.",10);
//CMessage("%One_ST_Stroke%");
//sleep(1000);
//setTempVar("AV_EdgeAV_FromVideo",true);
	//run("Custom" + java.io.File.separator + "AV_Scripts" + java.io.File.separator + "AV_EdgeAV.js");
//CMessage("wait10");
/*setStrokingNoTaunt(null);
CMessage("%Edge%");
    startEdging();
	CMessage("%stopstrokingedge%", null, false);
	CMessage("%lettheedgefade%")
sleep(20);
edge();
sleep(10);*/
//showImage("Images" + java.io.File.separator + "System" + java.io.File.separator + "Black.jpg");
//sleep(10);
//CMessage("I'm %Gonna% make you regret every single picture you have on that hard drive %Grin% %ShowTeaseImage%");
//CMessage("%startStroking%");
//sleep(10);
//CMessage("%stopstroking%", 0);
//stopStrokingAll();
//addContact(4);
//sleep(10);
//setStrokingNoTaunt(null,-1,4);
//sleep(10);
//removeContact(4);
//CMessage("%stopstroking%", 0);
//stopStrokingAll();
//sleep(10);
/*CMessage("%startStroking%");
sleep(10);
CMessage("%stopstroking%", 0);
sleep(10);*/
//Stroking();
//run("Structure" + java.io.File.separator + "Link" + java.io.File.separator + "AV_Link.js");
//run("Modules" + separator + "AV_ModGeneral38.js");//.Modulo3();
//setVar("sendDelay",-1);
//setVar("sendSender",1);
//run("Custom" + java.io.File.separator + "CallFromMod" + java.io.File.separator + "pvCall_FlagButtPlug.js");
//setTempVar("AV_PunishRND_Punish03",true);
//run("Custom" + java.io.File.separator + "CallReturn" + java.io.File.separator + "AV_PunishRND.js");
//setVar("AlternativeStroking_s02",true);
//run("Custom" + java.io.File.separator + "Shorts" + java.io.File.separator + "Short37.js");
//run("Custom" + separator + "AV_End" + separator + "AV_Cum09.js");
//run("Custom" + java.io.File.separator + "AV_Scripts" + java.io.File.separator + "Inter" + java.io.File.separator + "AV_Int_Pain.js");
//run("Custom" + separator + "CallReturn" + separator + "AV_RuinHMain.js");
//run("Custom" + separator + "Interact" + separator + "AV_PainInter.js");
//run("Custom" + separator + "Miniscripts" + separator + "pvMs_PunishMePlease.js");
//run("Custom" + java.io.File.separator + "pvLinkChastityNo" + java.io.File.separator + "LinkChNo03.js");
//run("Custom" + separator + "CRCBTBalls" + separator + "CRCBTB06.js");
//run("Custom" + separator + "h2sModules" + separator + "H2Stroke1.js");
//run("Interrupt" + java.io.File.separator + "pvIn_CBTBalls.js");
//run("Custom" + separator + "AV_Scripts" + separator + "AlternativeStroking.js");
//run("Custom" + java.io.File.separator + "AV_Start" + java.io.File.separator + "OrgasmCheck.js");
//run("Custom" + java.io.File.separator + "AV_Talk.js");
//run("Custom" + separator + "AV_Scripts" + separator + "AV_EdgeAV.js");
//run("Custom" + separator + "Edging" + separator + "Second.js");
//run("Custom" + separator + "RamdomLinks" + separator + "LinksRamdom20.js");
//run("Custom" + separator + "CallReturn" + separator + "Edge for us.js");
//run("Custom" + separator + "MiniScripts" + separator + "pvMs_WantToEatMyCum.js");
//run("Custom" + separator + "Modules" + separator + "AV_SpecGlitter1Module1.js");
//run("Custom" + separator + "Link" + separator + "AV_SpecGlitter3Link1.js");
//setVar("AV_taskOP9",true);
//setVar("AV_EdgeGoal",3);
//setVar("AV_EdgeRepeat",2);
//setVar("AV_EdgeReal",4);
//run("Interrupt" + separator + "AV_Controle.js");
//run("Interrupt" + separator + "pvInt_Punishment.js");
//run("Responses" + separator + "wantToBeAGoodBoy.js");
//run("test.js");
setVar("sendDelay",0);
setVar("sendSender",-1);
//cbt("both",0,3);
//customTask("AV_StrokePositions",0,4);
//run("Custom" + separator + "Tasks" + separator + "Spanking_First.js");
//DMessage("ApathyMoodIndex = "+getApathyMoodIndex());
//DMessage("Mood = "+getMood());
//CMessage("%Spanking%")
//SMessage("%Spanking%",-1,2)
DMessage("main: End");
//	Custom\AV_Scripts
