function chastityTaunts1Vocabulary() {
	DMessage("chastityTaunts1: VocabStart");
	separator = java.io.File.separator;
	let answers = [
		[null, "I bet you wish you could touch right now",null],
		[null, "I wish I could just pin you down and sit on your face right now #EmoteMoan",null],
		[null, "You're just counting the seconds until you get to #JerkOff again, aren't you #Lol",null],
		[null, "Are your #Balls starting to turn blue yet? #Giggles",null],
		[null, "Nope, none of this for you #Laugh","showCategoryImage(\"BLOWJOB\")"],
		[null, "That's pretty hot","showLocalPicture()"],
		[null, "Mmmm","showTeaseImage()"],
		[null, "Sexy","showTeaseImage()"],
		[null, "Nice","showTeaseImage()"],
		[null, "That's sexy","showTeaseImage()"],
		[null, "That's hot","showTeaseImage()"],
		[null, "So hot","showTeaseImage()"],
		[null, "The internet is just an endless supply of hotness #EmoteHappy","showTeaseImage()"],
		[null, "Don't mind me #EmoteRandom","showTeaseImage()"],
		[null, "There's no shortage of pictures to tease you with, that's for sure","showTeaseImage()"],
		[null, "I could just scroll through these porn blogs all day and never get bored","showTeaseImage()"],
		[null, "I bet this picture makes you wish you could #JerkOff right now...","showLocalPicture()"],
		[null, "I hope showing you some pictures now and then is enough to keep your arousal levels up #Smile","showTeaseImage()"],
		[null, "I love how many pictures there are online to tease you with #Lol","showTeaseImage()"],
		[null, "I wonder if this makes the ache worse for you","showTeaseImage()"],
		[null, "I don't think I could ever get tired of looking at pictures like this #Grin","showTeaseImage()"],
		[null, "This probably won't help your ache, but I'm #Gonna show it to you anyway #Lol","showTeaseImage()"],
		[null, "This should make you a little more desperate","showTeaseImage()"],
		[null, "Don't look at this picture I just found if you don't want to ache","showTeaseImage()"],
		[null, "So much sexiness in these blogs, too bad you can't enjoy it #Grin","showTeaseImage()"],
		[null, "This is pretty sexy","showTeaseImage()"],
		[null, "I wonder how much bluer your balls will get looking at this? #Grin","showTeaseImage()"],
		[null, "It's so much fun to tease you when there's nothing you can do about it #Giggles",null],
		[null, "You were born to be a submissive, #PetName",null],
		[null, "Obeying my commands give you purpose as well as pleasure",null],
		[null, "You have no idea how much I "+random("enjoy","love")+" seeing you suffer for me",null],
		[null, "When I see a pair of #Boobs like that, I just want to grab them #EmoteHappy","showCategoryImage(\"BOOBS\")"],
		[null, "I'm #Gonna make you regret every single picture you have on that hard drive #Grin","showLocalPicture()"],
		[null, "Oooh, I can see why you saved this one #Lol","showLocalPicture()"],
		[null, "I may have to save a copy of this one for myself #Grin","showLocalPicture()"],
		[null, "You have good taste in porn, I'll give you that much #Grin","showLocalPicture()"],
		[null, "I wonder what was going through your head when you saved <i>this</i> one #Grin","showLocalPicture()"],
		[null, "#EmoteMoan I fucking <i>love</i> this picture","showLocalPicture()"],
		[null, "It's so much fun going through your hard drive and finding pictures like <i>this</i> #Grin","showLocalPicture()"],
		[null, "This is almost as sexy as some of the stuff <i>I</i> say #Grin","showCategoryImage(\"CAPTIONS\")"],
		[null, "I'll have to remember some of these lines to use against you later #Grin","showCategoryImage(\"CAPTIONS\")"],
		[null, "Well, at least now I know how you liked to be talked to #Grin","showCategoryImage(\"CAPTIONS\")"],
		[null, "So this is the kind of stuff that turns you on huh? I'll remember that #Grin","showCategoryImage(\"CAPTIONS\")"],
		[null, "So this is the kind of girl you <i>really</i> want me to be huh? #Grin","showCategoryImage(\"CAPTIONS\")"],
		[null, null, "question(\"Are you getting frustrated yet? #Laugh\",\"youOwnMeResponse()\")"],
		//@ResponseYes(Frustrated)
		[null, null, "question(\"I bet you would love to lick that pussy, wouldn't you?\",\"wantToEatPussyResponse()\")","showCategoryImage(\"PUSSY\")"],
		//@ShowTaggedImage @TagBodyPussy @ResponseYes(WantToEatPussy)
		//@Flag(pthevCEI_No)
		["getVar(\"pthevCEI_No\",false)",null, "question(\"I bet if I don't let you #JerkOff long enough I could make you eat your cum #Grin\",\"wantToEatMyCumResponse()\",\"wantToEatMyCumDontResponse()\")"],
		//@ResponseYes(WantToEatMyCum) @ResponseNo(WantToEatMyCumDont)
		["!getVar(\"AV_SubKnees\",false)","%KneelForMe%",null],// @TempFlag(pvKneeling)
		["getVar(\"AV_SubKnees\",false)","%SitDown%",null],// @DeleteFlag(pvKneeling)
		//@RuinsOrgasm(Not,Never) Do you like it when I make you ruin your orgasm? @ResponseYes(ILikeRuiningMyOrgasm) @ResponseNo(IDontLikeRuiningMyOrgasm)
		["getVar(\"hasChastity\",false)","I bet time slows down when you're locked up #Laugh",null],
		["getVar(\"hasChastity\",false)","That chastity belt does look pretty tight",null],
		["getVar(\"hasChastity\",false)","If you do whatever I say, *maybe* I'll let you unlock it",null],
		["getVar(\"hasChastity\",false)","If your #Cock wasn't locked away right now, maybe you could rub it on this ass","showCategoryImage(\"BUTTS\")"],
		["getVar(\"hasChastity\",false)","I almost feel sorry for your trapped #Cock right now",null],
		["getVar(\"hasChastity\",false)","You, all the time now: \"at some point she will unlock me again, right???\" #Lol",null],
		["getVar(\"hasChastity\",false)","Being locked up may not be the most fun, but it's probably better for you",null],
		["getVar(\"hasChastity\",false)","Mmm look at those... too bad you can't even have an erection #Giggles","showCategoryImage(\"BOOBS\")"],
		["getVar(\"hasChastity\",false)","Finding out about your chastity cage is probably my favourite moment in our relationship",null],
		["getVar(\"hasChastity\",false)","I would never even let you close to my pussy without your cage on",null],
		["getVar(\"hasChastity\",false)","With my cock caged like that I could probably train you to worship my pussy properly",null],
		["getVar(\"hasChastity\",false)","I love trying to make you hard in that little cage #Grin",null],
		["getVar(\"hasChastity\",false)","I could watch you struggle with that cage all day long",null],
		["getVar(\"hasChastity\",false)","It must be so frustrating to see this and not be able to stroke","showTeaseImage()"],
		["getVar(\"hasChastity\",false)","Maybe I'll make this chastity thing permanent one day #Grin",null],
		["getVar(\"hasChastity\",false)","You must feel so powerless right now, with your #Cock locked up",null],
		["getVar(\"hasChastity\",false)","Is that #Cock pushing against the inside of the cage yet? #Smile",null],
		["getVar(\"hasChastity\",false)","Is my #Cock leaking precum yet? #Grin",null],
		["getVar(\"hasChastity\",false)","It must hurt so bad when I show you pictures like this one","showCategoryImage(\"BLOWJOB\")"],
		["getVar(\"hasChastity\",false)","That cage looks so damn cute on you #Giggles",null],
		["getVar(\"hasChastity\",false)","Remember when you used to take erections for granted? #Lol",null],
		["getVar(\"hasChastity\",false)","Knowing you're locked in that cage turns me on so much",null],
		["getVar(\"hasChastity\",false)","I'm so glad you told me about that chastity device",null],
		["getVar(\"hasChastity\",false)","A lot of women would probably love male chastity 'play' if they knew what it was all about ",null],
		["getVar(\"hasChastity\",false)","Chastity is good for you, you know that right?",null],
		["getVar(\"hasChastity\",false)","It's only a matter of time before you start to drip, drip, drip...",null],
		["getVar(\"hasChastity\",false)","I suppose they'd let you watch if you're wearing your cage #Smile","showCategoryImage(\"LESBIAN\")"],
		["getVar(\"hasChastity\",false)","Those #Balls must be so full... and there's just no way for them to get release #Giggles",null],
		["getVar(\"hasChastity\",false)","Does this make your #Balls ache? #Grin","showCategoryImage(\"BOOBS\")"],
		["getVar(\"hasChastity\",false)","I wonder how long it takes for your #Cock to forget how to get hard...",null],
		["getVar(\"hasChastity\",false)","If you asked nicely maybe she would deepthroat your cock cage? #Lol",null],
		["getVar(\"hasChastity\",false)","Does it hurt when you're #Cock tries to get hard in its cage?",null],
		["getVar(\"hasChastity\",false)","You can do the math: #SubName x Time In Chastity = a happy #DomHonorific #DomName",null],
		["getVar(\"hasChastity\",false)","The longer you're locked up, the more grateful you'll be when I let you #JerkOff again",null],
		["getVar(\"hasChastity\",false)","If anything, being locked up is a good reminder of who owns that #Cock",null],
		["getVar(\"hasChastity\",false)","I love the sight of a man in a chastity device, there should be more of those around",null],
		["getVar(\"hasChastity\",false)","I can't imagine ever letting anyone take away my ability to masturbate #EmoteRandom",null],
		["getVar(\"hasChastity\",false)","If it was the other way around, I would never let you deny me access to my pussy",null],
		["getVar(\"hasChastity\",false)","I love how submissive a guy gets the moment that lock snaps shut",null],
		["!getVar(\"hasChastity\",false)","I think male chastity is probably actually the greatest thing before or since sliced bread",null],
		["!getVar(\"hasChastity\",false)","I hope you #Cock isn't getting limp",null],
		["!getVar(\"hasChastity\",false)","You, all the time now: \"at some point she will let me stroke again, right???\" #Lol",null],
		["!getVar(\"hasChastity\",false)","The longer you're not allowed to touch, the more grateful you'll be when I let you #JerkOff again",null],
		["!getVar(\"hasChastity\",false)","Imagine how hard those lips would make your #Cock right now","showCategoryImage(\"BLOWJOB\")"],
		["!getVar(\"hasChastity\",false)","Try not to think too much about that thing in your lap, #PetName",null],
		["!getVar(\"hasChastity\",false)","It sucks not to be allowed to #JerkOff doesn't it? #Lol",null],
		["!getVar(\"hasChastity\",false)","You can put your hands behind your back if you have trouble keeping them off your #Cock",null],
		["!getVar(\"hasChastity\",false)","You can sit on your hands if you want #Giggles",null],
		["!getVar(\"hasChastity\",false)","You must be soooo anxious to start #JerkingOff again",null],
		["!getVar(\"hasChastity\",false)","Try keep keep it hard, flex those little cock muscles, #PetName",null],
		["getVar(\"pvMadeKeyholder\",false)","I'm going to make you regret giving me the key to your cage #Grin",null],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null,null,"showLocalPicture()"],
		[null, "The male is giving honor to his Domme by allowing her to keep his most private area locked away for her use only.",null],
		[null, "Keeping a man in chastity allows the Domme to have a say when he is given the honor of having sex with her.",null],  
		[null, "Men often think that they can demand their Dommes to have sex anytime.  This is not being very considerate. ",null], 
		[null, "The man should consider it a great honor to have his Domme allow him to be inside of her and enjoying their intimacy together.",null],
		[null, "In fact, the man should even ask permission to enter his Domme, showing her honor in this way.",null],  
		[null, "After they have intercourse, the man should thank his Domme for the honor of having her as his Domme and for allowing him to have sex with her.",null],
		[null, "A man in chastity cannot masturbate, which is a frequent problem with men. ",null],
		[null, "A man in chastity will have his focus on his Domme. ",null],
		[null, "It should not take a chastity device to make the man be this way, but sometimes it can be a help.",null],
		[null, "A chastity device can be a good training device used by a loving and thoughtful Domme to help her submissive man “learn” how to be the submissive he ought to be.",null],
		[null, "There is a heightened level of sexual intimacy that is achieved by keeping a man in chastity.",null],
		[null, "While he is locked up, the Domme can have her sexual needs met by him in various ways.",null],
		[null, "Chastity is not fun for me if you don't suffer",null],
		[null, "Chastity keeps pets focused",null],
		[null, "You can't imagine how much I love opening a slave's cage just to ruin their orgasm",null],
		[null, "Hope you feel comfortable wearing that cage in your little cock, because I don't like opening it",null],
		[null, "Only caged boys are useful",null],
		["(getVar(\"AV_Beta\",false)||getVar(\"pvBeta\",false))","Betas should remain denied in chastity forever.",null],
		[null, "The idea of locking a #PetName permanently always gets me horny",null],
		["(getVar(\"AV_Beta\",false)||getVar(\"pvBeta\",false))","The best way to control beta males",null],
		[null, "Chastity makes boys better at licking",null],
		[null, "I want to lock you permanently and tease you merciless until you cry",null],
		[null, "Your useless cock should remain locked at all times",null],
		[null, "After being locked for as long as I want, you'll be rewarded a ruined orgasm, #PetName!",null],
		[null, "I don't want to unlock you",null],
		["(getVar(\"av_fetish_rough\",false)||getVar(\"AV_DommeMistress\",false))","I'm gonna ruin you and I'll have you crying.",null],
		["(getVar(\"av_fetish_rough\",false)||getVar(\"AV_DommeMistress\",false))","I am going to be cruel to you until you cry and never want to come back again. ",null],
		["getVar(\"av_fetish_humiliating\",false)", null, "question(\"You're such a mindless little stroker, aren't you?\",\"youOwnMeResponse()\",\"iAmNotYourBitchResponse()\")"],// @ResponseYes(YouOwnMe) @ResponseNo(IAmNotYourBitch)
		["getVar(\"av_fetish_humiliating\",false)","Just a douche who'll do anything I tell him to do.",null],
		[null, "I told you I own your cock and this will serve as a reminder for the time being!",null]
		];
	
	execRndLine(answers);
	
	DMessage("chastityTaunts1: VocabEnd");
	return "<dontsend>";
}