function edgeVocabulary()
{
	let answers = ["Get to the %EdgeNoun%",
	"Get to the %EdgeNoun% for me", 
    "I want you to get %NearTheEdge%",
    "Edge for me",
    "Edge now, %PetName%",
    "Edge for me %PetName%",
    "Get %NearTheEdge%, %PetName%",
    "Get %NearTheEdge%, %SubName%",
    "Now... <i>Edge!</i>",
    "Now, edge hard for me.  <i>HARD!</i>",
    "Edge for me %PetName%. %Now%",
    "Time to get on the edge! %EmoteHappy% %Now%",
    "Edge that %Cock% for me, %PetName%.  %Now%",
    "I want you on the edge, %Now%",
    "%Lol%, now edge!",
    "Time for an edge %PetName%. %Now%",
    "Get on the edge for me!",
    "Get on the %EdgeNoun% for me!",
    "I want you at the edge!",
    "I want you at the %EdgeNoun%!",
    "Hit the edge!",
    "Hit the %EdgeNoun%!",
    "Now, edge hard for me.",
    "Edge. Now.",
    "Edge. Now!",
    "Edge... Now.",
    "I want you to Edge.",
    "Give me that Edge!",
    "I want to see you Edge!",
    "Edge, baby.",
    "Edge, baby!",
    "Time to Edge!",
    "Time to Edge.",
    "Edge! Give it to me!"];
    //playAudio("Audio" + java.io.File.separator + "tease" + java.io.File.separator + "cEdge.mp3");
	return answers[randomInteger(0, answers.length - 1)];
}