main();
//call api customTask(task = "AV_StrokePositions", delay = 0, sender = -1, rounds = 3)
//see helperFunctions.js
//direct call will send only one line
function main(){
	DMessage("AV_StrokePositions_First Task: Beginning");
	let answers = [ 
    [null,"%KneelForMe% and give me 10 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 20 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 30 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 40 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 50 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 60 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 70 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 90 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 80 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 100 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(4)","%KneelForMe% and give me 80 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(5)","%KneelForMe% and give me 100 %Crazy% fast strokes",null],
    [null,"%KneelForMe% and give me 10 strokes",null],
    [null,"%KneelForMe% and give me 20 strokes",null],
    [null,"%KneelForMe% and give me 30 strokes",null],
    [null,"%KneelForMe% and give me 40 strokes",null],
    [null,"%KneelForMe% and give me 50 strokes",null],
    [null,"%KneelForMe% and give me 60 strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 70 strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 90 strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 80 strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 100 strokes",null],
    ["checkOldDommeLevel(4)","%KneelForMe% and give me 80 strokes",null],
    ["checkOldDommeLevel(5)","%KneelForMe% and give me 100 strokes",null],
    [null,"%KneelForMe% and give me 10 strokes",null],
    [null,"%KneelForMe% and give me 20 strokes",null],
    [null,"%KneelForMe% and give me 30 strokes",null],
    [null,"%KneelForMe% and give me 40 strokes",null],
    [null,"%KneelForMe% and give me 50 strokes",null],
    [null,"%KneelForMe% and give me 60 strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 70 strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 90 strokes",null],
    ["checkOldApathyLevel(4)","%KneelForMe% and give me 80 strokes",null],
    ["checkOldApathyLevel(5)","%KneelForMe% and give me 100 strokes",null],
    ["checkOldDommeLevel(4)","%KneelForMe% and give me 80 strokes",null],
    ["checkOldDommeLevel(5)","%KneelForMe% and give me 100 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 10 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 20 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 30 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 40 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 50 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 60 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 70 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 90 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 80 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 100 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 80 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 100 %Crazy% fast strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 10 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 20 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 30 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 40 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 50 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 60 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 70 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 90 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 80 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 100 strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 80 strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and give me 100 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  10 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  20 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  30 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  40 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  50 strokes",null],
    ["getVar(\"av_basic_position\", false)","Get into the Basic Position and  60 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  70 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  90 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  80 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  100 strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  80 strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_basic_position\", false)","Get into the Basic Position and  100 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 10 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 20 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 30 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 40 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 50 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 60 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 70 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 90 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 %Crazy% fast strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 %Crazy% fast strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 %Crazy% fast strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 10 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 20 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 30 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 40 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 50 strokes",null],
    ["getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 60 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 70 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 90 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 70 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 90 strokes",null],
    ["checkOldApathyLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 strokes",null],
    ["checkOldApathyLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 strokes",null],
    ["checkOldDommeLevel(4) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 80 strokes",null],
    ["checkOldDommeLevel(5) && getVar(\"av_standing_position\", false)","Get into the Stand Position and give me 100 strokes",null] ];

	execRndLine(answers);
	
	DMessage("AV_StrokePositions_First Task: End");
	return;
}